tg_bot_api_token: "5976184486:AAHoh-NUAKnYWScusquGfWudIZqCVeJDW-E"
tg_bot_admins:
  - 102261660
tg_bot_users:
  - tg_bot_user_id: 102261660
    tg_bot_user_name: "Igor"
  - tg_bot_user_id: 5898130100
    tg_bot_user_name: 'Igor Tinkoff'
  - tg_bot_user_id: 123456789
    tg_bot_user_name: 'Igor KZ'